# Generated by Django 4.0 on 2023-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='phoneNumber',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
